#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'chef-solo-search'
# cookbook 'users', git: 'git@github.com:sethvargo-cookbooks/users.git'
cookbook 'user', git: 'git@github.com:fnichol/chef-user.git'
cookbook 'sudo'
cookbook 'build-essential'
cookbook 'ohai'
cookbook 'git'
cookbook 'openssl'
cookbook 'nginx'
cookbook 'redisio', git: 'git://github.com/brianbianco/redisio.git'
cookbook 'chef-puma', git: 'git://github.com/yourabi/chef-puma.git'
cookbook 'rvm', :git => 'git://github.com/fnichol/chef-rvm.git'
cookbook 'postgresql', :git => 'git://github.com/phlipper/chef-postgresql.git'
